---
title: "Group_1_Project"
author: "Matthew Runyon"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
tree_rings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')

library(ggplot2)

ggplot(sulfur, aes(x=year, y=neem))+
  geom_line()+
  ggtitle("Sulfur Concentration per Year from NEEM Ice Cores")+
  labs(x="Year (AD)", y="Sulfur Content (ng/g)")+
  theme(panel.grid=element_blank())

ggplot(sulfur, aes(x=year, y=wdc))+
  geom_line()+
  ggtitle("Sulfur Concentration per Year from WDC Ice Cores")+
  labs(x="Year (AD)", y="Sulfur Content (ng/g)")+
  theme(panel.grid=element_blank())

ggplot(tree_rings, aes(x=year, y=n_tree))+
  geom_line()+
  ggtitle("Tree Ring Z-Scores per Year")+
  labs(x="Year (AD)", y="Z-Score")+
  theme(panel.grid=element_blank())

ggplot(tree_rings, aes(x=year, y=europe_temp_index))+
  geom_line()+
  ggtitle("European Temperature Index per Year")+
  labs(x="Year (AD)", y="European Temperature Index")+
  theme(panel.grid=element_blank())

```

